package org.application.core.elements;

public enum ElementType {
    HTML_DIV,
    HTML_HEAD,
    HTML_BODY,
    HTML_BOLD,
    HTML_LINK,
    HTML_INPUT,
    HTML_BUTTON,
    HTML_FOOTER,
    HTML_DOCUMENT,
    HTML_FORMULARY,
    HTML_HEADING_1,
    HTML_HEADING_2,
    HTML_HEADING_3,
    HTML_HEADING_4,
    HTML_HEADING_5,
    HTML_HEADING_6,
    HTML_LIST_ITEM,
    HTML_PARAGRAPH,
    HTML_LINE_BREAK,
    HTML_UNORDERED_LIST,
}
